---
version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/template-cnb"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
