api = "0.2"

[buildpack]
  id = "{{ .Organization }}/{{ .Buildpack }}"
  homepage = "https://github.com/{{ .Organization }}/{{ .Buildpack }}"
  name = "Paketo {{ .Buildpack | Title }} Buildpack"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]
  include_files = ["bin/run","bin/build","bin/detect","buildpack.toml"]
  pre_package = "./scripts/build.sh"
